DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - CSS_SCSS_LINT
  - HTML_DJLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - POWERSHELL_POWERSHELL
  - SPELL_CSPELL
  - CSS_STYLELINT
  - JSON_JSONLINT
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - SPELL_LYCHEE
  - YAML_V8R

REPOSITORY_CHECKOV_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true
DOCKERFILE_HADOLINT_FILTER_REGEX_EXCLUDE: ^\.devcontainer/Dockerfile$