version: "3.8"

# TODO: test this, figure out proper HTTPS/SSL setup
services:
  social-coder-api-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-awesome-password
      - MYSQL_DATABASE='social-coder'
    volumes:
      - C:\Users\Will_\RiderProjects\Social-Coder\Database:/var/lib/mysql
        
  social-coder-api:
    build:
      context: .
      dockerfile: SocialCoder.Web/Server/Dockerfile
    environment:
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7159:443"
    volumes:
      - $USERPROFILE\.aspnet\https:/https/
    depends_on:
      - social-coder-api-db
      
    