version: "3.8"

# TODO: test this, figure out proper HTTPS/SSL setup
services:
  social-coder-api-db:
    container_name: social-coder-api-db
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  social-coder-api:
    build:
      context: .
      dockerfile: SocialCoder.Web/Server/Dockerfile
    environment:
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_CA_AUTH_PASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${CERT_CA_AUTH_NAME}.crt
    ports:
      - "7159:443"
    volumes:
      - ${PROJECT_PATH}\SSL:/https
    depends_on:
      - social-coder-api-db
    
    